[package]
name = "moma"
version = "0.2.1"
edition = "2024"
authors = ["Neil Crago <n.j.crago@gmail.com>"]
description = "Moving Origin Modular Arithmetic (MOMA), a library for modeling complex systems"
license = "MIT OR Apache-2.0"
repository = "https://github.com/neil-crago/moma"
keywords = ["inertia", "math", "modulo", "cosmology", "gravity"]
include = [
    "src/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[dependencies]
arima = "0.3.0"
rustfft = "6.4.0"


