[package]
name = "moma"
version = "0.1.0"
edition = "2024"
authors = ["Neil Crago <n.j.crago@gmail.com>"]
description = "A Rust library for managing and manipulating data in a modular way."
license = "MIT OR Apache-2.0"
repository = "https://github.com/neil-crago/moma"
include = ["examples/**", "src/lib.rs", "tests/**", "Cargo.toml", "README.md", "LICENSE-MIT", "LICENSE-APACHE"]


[dependencies]


